version: "3.6"

services:
    downloader:
        ports:
            - 127.0.0.1:5000:5000
        build: .
        volumes:
            - type: bind
              source: ./downloads # in nextcloud /zwembad/nextcloud/data/files/...
              target: /downloads
        user: "1000"
