version: "3.6"

services:

  music:
    ports:
      - 8080:8080
    build: .
    volumes:
      - type: bind
        source: ./music
        target: /music
      - type: bind
        source: ./data
        target: /data
    user: "1000"
    environment:
      TZ: Europe/Amsterdam
