version: "3.6"

services:

  music:
    ports:
      - 127.0.0.1:5000:8080
    build: .
    volumes:
      - type: bind
        source: ./music # in nextcloud /zwembad/nextcloud/data/files/...
        target: /music
    user: "1000"
