version: "3.6"

services:

  music:
    ports:
      - 8080:8080
    build: .
    volumes:
      - type: bind
        source: ./music # in nextcloud /zwembad/nextcloud/data/files/...
        target: /music
      - type: bind
        source: ./cache
        target: /cache
      - type: bind
        source: ./data
        target: /data
    user: "1000"
    environment:
      TZ: Europe/Amsterdam
      MUSIC_RADIO_PLAYLISTS: 'CB;DK;JK;Guest-Robin'
      MUSIC_RADIO_ANNOUNCEMENTS_PLAYLIST: 'RR'
      MUSIC_LASTFM_API_KEY: b6eefad5832d7a4f73324b1614411137
      MUSIC_LASTFM_API_SECRET: 03037dc0291a39ab6cc80ca486c5c64a
