version: "3.6"

services:

  music:
    ports:
      - 127.0.0.1:8080:8080
    build: .
    depends_on: [redis]
    volumes:
      - type: bind
        source: ./music # in nextcloud /zwembad/nextcloud/data/files/...
        target: /music
      - type: bind
        source: ./cache
        target: /cache
    user: "1000"
    environment:
      MUSIC_WEB_PASSWORD: 1234
      MUSIC_REDIS_HOST: redis

  redis:
    image: redis
