version: "3.6"

services:

  music:
    ports:
      - 127.0.0.1:5000:8080
    build: .
    volumes:
      - type: bind
        source: ./music # in nextcloud /zwembad/nextcloud/data/files/...
        target: /music
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: '128M'
    user: "1000"
    environment:
      MUSIC_WEB_PASSWORD: 1234
